import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/hero'
import Companies from '@/components/companies'
import Steps from '@/components/steps'
import Servicefor from '@/components/servicefor'
import Testimonials from '@/components/testimonials'
import Contact from '@/components/contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
      <div className="sr-only">
        <a href="https://dotenv.in">https://dotenv.in</a>
      </div>
    <Hero />
    <Companies />
    <Steps />
    <Servicefor />
    <Testimonials />
    <Contact />
      </main>
    </>
  )
}
